server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl-auto: update

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sm
        username: root
        password: 123456

    main:
        allow-circular-references: true

app:
    client:
        url: http://localhost:3000/

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days