import type {Metadata} from 'next'
import {Inter as FontSans} from 'next/font/google'
import localFont from "next/font/local"

import './globals.css'
import {cn} from "@/lib/utils"
import {Toaster} from "@/components/ui/toaster"
import {Analytics} from "@/components/analytics"
import {TailwindIndicator} from "@/components/tailwind-indicator"
import {ThemeProvider} from "@/components/theme-provider"
import React from "react";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

const fontHeading = localFont({
    src: "../assets/fonts/CalSans-SemiBold.woff2",
    variable: "--font-heading",
})


export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <head/>
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable,
                fontHeading.variable
            )}
        >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
            <Analytics/>
            <Toaster/>
            <TailwindIndicator/>
        </ThemeProvider>
        </body>
        </html>
    )
}
